#!/usr/bin/env python3
"""ledslave_countdown_editor_en.py — GUI wrapper for generating countdown frame headers.

Loads seven base images (ready / 5 / 4 / 3 / 2 / 1 / go) from a folder, lets
the user describe the physical LED wiring (start corner, traversal direction,
zigzag/serpentine), visualises the resulting strip path so it can be matched
to the real panel, and writes the seven PROGMEM .h headers consumed by
ledslave_countdown.ino.

This tool does NOT edit pixels. The matrix size is the source image's own
pixel size — all seven images must share the same dimensions.

English UI edition. The Japanese edition is ledslave_countdown_editor.py;
both produce identical header output.
"""

import sys
from pathlib import Path
from tkinter import Tk, Frame, Label, Button, Canvas, StringVar, IntVar, \
    filedialog, messagebox, LEFT, RIGHT, TOP, BOTH, X, Y, W as TK_W, E as TK_E
from tkinter import ttk

try:
    from PIL import Image, ImageTk
except ImportError:
    print("ERROR: Pillow is required. Install with: pip install Pillow",
          file=sys.stderr)
    sys.exit(2)


STANDARD_FRAMES = [
    ("ready", "frame_ready"),
    ("5",     "frame_5"),
    ("4",     "frame_4"),
    ("3",     "frame_3"),
    ("2",     "frame_2"),
    ("1",     "frame_1"),
    ("go",    "frame_go"),
]

ACCEPTED_EXTS = (".bmp", ".png", ".jpg", ".jpeg")

START_CORNERS = [("Top-left", "TL"), ("Top-right", "TR"),
                 ("Bottom-left", "BL"), ("Bottom-right", "BR")]
DIRECTIONS    = [("Horizontal (row-major)", "H"), ("Vertical (column-major)", "V")]

THUMB_MAX = 96       # px per side for frame thumbnails
WIRING_MAX = 360     # px per side for the wiring diagram canvas


# --------------------------------------------------------------------------
# Strip-order mapping
# --------------------------------------------------------------------------

def strip_order(w: int, h: int, start: str, direction: str, zigzag: bool):
    """Yield (x, y) in physical-strip order for the given wiring.

    start     : 'TL' | 'TR' | 'BL' | 'BR' — which corner has LED #0
    direction : 'H' (row-major: snake along rows) | 'V' (column-major)
    zigzag    : True if alternate rows/columns reverse (serpentine)
    """
    if direction == "H":
        # Outer: rows. Top-down if start is T*, bottom-up if start is B*.
        ys = range(h) if start in ("TL", "TR") else range(h - 1, -1, -1)
        # First-row direction: L→R if start is *L, R→L if start is *R.
        first_l2r = start in ("TL", "BL")
        for i, y in enumerate(ys):
            reverse = zigzag and (i & 1)
            l2r = first_l2r ^ reverse
            xs = range(w) if l2r else range(w - 1, -1, -1)
            for x in xs:
                yield x, y
    else:
        # Outer: columns. Left→right if start is *L, right→left if *R.
        xs = range(w) if start in ("TL", "BL") else range(w - 1, -1, -1)
        # First-column direction: T→B if start is T*, B→T if start is B*.
        first_t2b = start in ("TL", "TR")
        for i, x in enumerate(xs):
            reverse = zigzag and (i & 1)
            t2b = first_t2b ^ reverse
            ys = range(h) if t2b else range(h - 1, -1, -1)
            for y in ys:
                yield x, y


# --------------------------------------------------------------------------
# Header writer (compatible with bmp2header.py output format)
# --------------------------------------------------------------------------

def write_header(out_path: Path, var_name: str, img: Image.Image,
                 start: str, direction: str, zigzag: bool, source: str) -> None:
    w, h = img.size
    px = img.load()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    guard = var_name.upper() + "_H"
    name_upper = var_name.upper()
    wiring_note = (f"start={start} dir={'row-major' if direction == 'H' else 'column-major'} "
                   f"{'serpentine' if zigzag else 'progressive'}")

    with out_path.open("w", encoding="utf-8") as f:
        f.write(f"// Generated by ledslave_countdown_editor_en.py from {source}.\n")
        f.write(f"// {w} x {h} pixels, {wiring_note} — do not edit by hand; regenerate instead.\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write(f"#include <Arduino.h>\n\n")
        f.write(f"#define {name_upper}_WIDTH  {w}\n")
        f.write(f"#define {name_upper}_HEIGHT {h}\n")
        f.write(f"#define {name_upper}_SERPENTINE {1 if zigzag else 0}\n\n")
        f.write(f"const uint8_t {var_name}[{w * h * 3}] PROGMEM = {{\n")

        triples = []
        for x, y in strip_order(w, h, start, direction, zigzag):
            r, g, b = px[x, y]
            triples.append(f"0x{r:02X},0x{g:02X},0x{b:02X}")

        # 16 pixels per line for readability.
        per_line = 16
        for i in range(0, len(triples), per_line):
            line = ", ".join(triples[i:i + per_line])
            f.write(f"    {line},\n")
        f.write("};\n\n")
        f.write(f"#endif // {guard}\n")


# --------------------------------------------------------------------------
# GUI
# --------------------------------------------------------------------------

class EditorApp:
    def __init__(self, root: Tk):
        self.root = root
        root.title("ledslave_countdown editor")

        # Default input dir: same folder as this script. Default output dir:
        # led/ledslave_countdown/images relative to this script.
        script_dir = Path(__file__).resolve().parent
        default_out = (script_dir.parent / "ledslave_countdown" / "images").resolve()

        self.in_dir: Path = script_dir
        self.out_dir: Path = default_out if default_out.is_dir() else script_dir
        self.images: dict[str, Image.Image] = {}
        self.image_paths: dict[str, Path] = {}
        self.matrix_w = 0
        self.matrix_h = 0

        self.start_var = StringVar(value="TL")
        self.dir_var = StringVar(value="H")
        self.zigzag_var = IntVar(value=0)

        self._build_ui()

        # Try to auto-load from the default folder silently — if all 7 frames
        # happen to sit next to the script, the user can start working
        # immediately without clicking through a folder picker.
        self._load_folder(self.in_dir, silent=True)

    # ---- UI construction -------------------------------------------------

    def _build_ui(self) -> None:
        root = self.root

        # Row 1: input folder picker
        top = Frame(root, padx=8, pady=6)
        top.pack(fill=X)
        Button(top, text="Input folder…", command=self._pick_input).pack(side=LEFT)
        self.in_lbl = Label(top, text=str(self.in_dir), anchor="w")
        self.in_lbl.pack(side=LEFT, fill=X, expand=True, padx=8)
        self.size_lbl = Label(top, text="Size: —", width=14, anchor="e")
        self.size_lbl.pack(side=RIGHT)

        # Row 2: frame thumbnails
        mid = ttk.LabelFrame(root, text="Loaded frames", padding=6)
        mid.pack(fill=X, padx=8)
        self.thumb_frame = Frame(mid)
        self.thumb_frame.pack()
        self.thumb_labels: dict[str, Label] = {}
        self.thumb_imgs: dict[str, ImageTk.PhotoImage] = {}
        for stem, _ in STANDARD_FRAMES:
            col = Frame(self.thumb_frame, padx=4)
            col.pack(side=LEFT)
            lbl = Label(col, text=stem, font=("", 9, "bold"))
            lbl.pack()
            img_lbl = Label(col, text="—", width=12, height=6,
                            relief="sunken", bg="#222", fg="#888")
            img_lbl.pack()
            self.thumb_labels[stem] = img_lbl

        # Row 3: wiring controls + wiring preview side by side
        body = Frame(root, padx=8, pady=8)
        body.pack(fill=BOTH, expand=True)

        controls = ttk.LabelFrame(body, text="LED wiring", padding=8)
        controls.pack(side=LEFT, fill=Y)

        Label(controls, text="Start point (LED #0)", font=("", 9, "bold")).grid(row=0, column=0, columnspan=2, sticky=TK_W)
        for i, (label, val) in enumerate(START_CORNERS):
            ttk.Radiobutton(controls, text=label, variable=self.start_var,
                            value=val, command=self._redraw_wiring
                            ).grid(row=1 + i // 2, column=i % 2, sticky=TK_W, padx=4)

        Label(controls, text="").grid(row=3, column=0)
        Label(controls, text="Traversal direction", font=("", 9, "bold")).grid(row=4, column=0, columnspan=2, sticky=TK_W)
        for i, (label, val) in enumerate(DIRECTIONS):
            ttk.Radiobutton(controls, text=label, variable=self.dir_var,
                            value=val, command=self._redraw_wiring
                            ).grid(row=5 + i, column=0, columnspan=2, sticky=TK_W, padx=4)

        Label(controls, text="").grid(row=7, column=0)
        ttk.Checkbutton(controls, text="Zigzag (serpentine)",
                        variable=self.zigzag_var, command=self._redraw_wiring
                        ).grid(row=8, column=0, columnspan=2, sticky=TK_W)

        Label(controls, text="").grid(row=9, column=0)
        ttk.Separator(controls, orient="horizontal").grid(row=10, column=0, columnspan=2, sticky="ew", pady=4)
        Button(controls, text="Output folder…", command=self._pick_output).grid(row=11, column=0, columnspan=2, sticky="ew", pady=(4, 2))
        self.out_lbl = Label(controls, text=str(self.out_dir), wraplength=200, justify="left", fg="#555")
        self.out_lbl.grid(row=12, column=0, columnspan=2, sticky=TK_W)
        Button(controls, text="Export", command=self._export,
               bg="#2563eb", fg="white").grid(row=13, column=0, columnspan=2, sticky="ew", pady=(6, 0))

        # Wiring preview
        preview = ttk.LabelFrame(body, text="Wiring preview (LED #0 → end of strip)", padding=6)
        preview.pack(side=LEFT, fill=BOTH, expand=True, padx=(10, 0))
        self.wiring_canvas = Canvas(preview, width=WIRING_MAX, height=WIRING_MAX,
                                    bg="#111", highlightthickness=0)
        self.wiring_canvas.pack()
        self.legend_lbl = Label(preview, text="Green = start (LED #0)   Red = end   Arrow = data flow direction",
                                fg="#555")
        self.legend_lbl.pack(pady=(4, 0))

        self._redraw_wiring()

    # ---- File picking ----------------------------------------------------

    def _pick_input(self) -> None:
        d = filedialog.askdirectory(title="Select the folder containing the base images",
                                    initialdir=str(self.in_dir))
        if not d:
            return
        self._load_folder(Path(d))

    def _pick_output(self) -> None:
        d = filedialog.askdirectory(title="Select the output folder",
                                    initialdir=str(self.out_dir))
        if not d:
            return
        self.out_dir = Path(d)
        self.out_lbl.config(text=str(self.out_dir))

    def _load_folder(self, src: Path, silent: bool = False) -> None:
        found: dict[str, Path] = {}
        missing = []
        for stem, _ in STANDARD_FRAMES:
            hit = None
            for ext in ACCEPTED_EXTS:
                cand = src / (stem + ext)
                if cand.exists():
                    hit = cand
                    break
            if hit:
                found[stem] = hit
            else:
                missing.append(stem)

        if missing:
            self.in_lbl.config(text=f"{src}  (images not found)")
            if not silent:
                messagebox.showwarning(
                    "Missing images",
                    f"Frames not found: {', '.join(missing)}\n\n"
                    "File names must be one of ready / 1 / 2 / 3 / 4 / 5 / go,\n"
                    f"with one of these extensions: {', '.join(ACCEPTED_EXTS)}."
                )
            return

        images: dict[str, Image.Image] = {}
        sizes = set()
        for stem, path in found.items():
            img = Image.open(path).convert("RGB")
            images[stem] = img
            sizes.add(img.size)

        if len(sizes) > 1:
            detail = "\n".join(f"  {s}: {images[s].size[0]}×{images[s].size[1]}" for s in images)
            if not silent:
                messagebox.showerror(
                    "Size mismatch",
                    "All 7 images must have the same pixel size.\n\n" + detail
                )
            return

        w, h = sizes.pop()
        self.in_dir = src
        self.images = images
        self.image_paths = found
        self.matrix_w, self.matrix_h = w, h

        self.in_lbl.config(text=str(src))
        self.size_lbl.config(text=f"Size: {w}×{h}")
        self._refresh_thumbs()
        self._redraw_wiring()

    # ---- Thumbnails ------------------------------------------------------

    def _refresh_thumbs(self) -> None:
        if not self.images:
            return
        w, h = self.matrix_w, self.matrix_h
        scale = max(1, min(THUMB_MAX // max(w, 1), THUMB_MAX // max(h, 1)))
        tw, th = w * scale, h * scale
        for stem, _ in STANDARD_FRAMES:
            img = self.images[stem].resize((tw, th), Image.NEAREST)
            ph = ImageTk.PhotoImage(img)
            self.thumb_imgs[stem] = ph  # keep ref
            self.thumb_labels[stem].config(image=ph, text="", width=tw, height=th)

    # ---- Wiring preview --------------------------------------------------

    def _redraw_wiring(self) -> None:
        c = self.wiring_canvas
        c.delete("all")

        w = self.matrix_w or 8
        h = self.matrix_h or 8

        # Cell size that fits WIRING_MAX with at least 1px margin.
        margin = 14
        cell = max(8, min((WIRING_MAX - 2 * margin) // w, (WIRING_MAX - 2 * margin) // h))
        grid_w = cell * w
        grid_h = cell * h
        ox = (WIRING_MAX - grid_w) // 2
        oy = (WIRING_MAX - grid_h) // 2

        # Grid cells.
        for y in range(h):
            for x in range(w):
                x0 = ox + x * cell
                y0 = oy + y * cell
                c.create_rectangle(x0, y0, x0 + cell, y0 + cell,
                                   outline="#333", fill="#1a1a1a", width=1)

        # Strip path.
        order = list(strip_order(w, h,
                                 self.start_var.get(),
                                 self.dir_var.get(),
                                 bool(self.zigzag_var.get())))

        def center(x, y):
            return ox + x * cell + cell // 2, oy + y * cell + cell // 2

        # Polyline through every cell.
        pts = []
        for x, y in order:
            cx, cy = center(x, y)
            pts.extend((cx, cy))
        if len(pts) >= 4:
            c.create_line(*pts, fill="#3b82f6", width=max(1, cell // 8),
                          capstyle="round", joinstyle="round")

        # Direction arrows: small arrowhead every K cells along the path.
        if cell >= 12 and len(order) >= 2:
            step = max(1, min(w, h))  # one arrow per row/column
            for i in range(step, len(order), step):
                ax, ay = center(*order[i - 1])
                bx, by = center(*order[i])
                # Skip arrows on zero-length segments.
                if (ax, ay) != (bx, by):
                    c.create_line(ax, ay, bx, by, fill="#60a5fa",
                                  width=max(1, cell // 8),
                                  arrow="last",
                                  arrowshape=(cell // 2, cell // 2, cell // 4))

        # Start / end markers.
        if order:
            sx, sy = center(*order[0])
            ex, ey = center(*order[-1])
            r = max(3, cell // 3)
            c.create_oval(sx - r, sy - r, sx + r, sy + r, fill="#22c55e", outline="")
            c.create_oval(ex - r, ey - r, ex + r, ey + r, fill="#ef4444", outline="")
            if cell >= 14:
                c.create_text(sx, sy, text="0", fill="#000", font=("", max(6, cell // 3), "bold"))
                c.create_text(ex, ey, text=str(len(order) - 1), fill="#fff",
                              font=("", max(6, cell // 4), "bold"))

        self.legend_lbl.config(
            text=(f"{w}×{h} = {w*h} LEDs  /  "
                  f"start={self.start_var.get()}  "
                  f"direction={'Horizontal (row-major)' if self.dir_var.get()=='H' else 'Vertical (column-major)'}  "
                  f"zigzag={'on' if self.zigzag_var.get() else 'off'}")
        )

    # ---- Export ----------------------------------------------------------

    def _export(self) -> None:
        if not self.images:
            messagebox.showwarning("No images loaded", "Please select an input folder first.")
            return
        if not self.out_dir.exists():
            try:
                self.out_dir.mkdir(parents=True, exist_ok=True)
            except OSError as e:
                messagebox.showerror("Output error", f"{self.out_dir}\n{e}")
                return

        start = self.start_var.get()
        direction = self.dir_var.get()
        zigzag = bool(self.zigzag_var.get())
        written = []
        for stem, var in STANDARD_FRAMES:
            img = self.images[stem]
            src = self.image_paths[stem].name
            out_path = self.out_dir / (stem + ".h")
            write_header(out_path, var, img, start, direction, zigzag, src)
            written.append(out_path.name)

        messagebox.showinfo(
            "Export complete",
            f"Output folder: {self.out_dir}\n\nFiles written:\n  " + "\n  ".join(written)
        )


def main() -> None:
    root = Tk()
    try:
        root.tk.call("tk", "scaling", 1.2)
    except Exception:
        pass
    EditorApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
